CREATE TABLE `gm_transfer_npc` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sender_name` varchar(100) NOT NULL DEFAULT '',
  `receiver_name` varchar(100) NOT NULL DEFAULT '',
  `nameid` int(11) unsigned NOT NULL DEFAULT 0,
  `amount` int(11) unsigned NOT NULL DEFAULT 0,
  `refine` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `card0` int(10) unsigned NOT NULL DEFAULT 0,
  `card1` int(10) unsigned NOT NULL DEFAULT 0,
  `card2` int(10) unsigned NOT NULL DEFAULT 0,
  `card3` int(10) unsigned NOT NULL DEFAULT 0,
  `message` varchar(256) NOT NULL DEFAULT '',
  `sent_date` datetime DEFAULT '1900-01-01 00:00:00',
  `received_date` datetime DEFAULT '1900-01-01 00:00:00',
  `status` tinyint(3) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


CREATE TABLE `admin_generate_item` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `gm_name` varchar(32) NOT NULL,
  `name` varchar(32) NOT NULL,
  `rewards_reason` varchar(300) NOT NULL,
  `itemid1` int(11) NOT NULL,
  `amount1` int(11) NOT NULL,
  `itemid2` int(11) NOT NULL,
  `amount2` int(11) NOT NULL,
  `itemid3` int(11) NOT NULL,
  `amount3` int(11) NOT NULL,
  `itemid4` int(11) NOT NULL,
  `amount4` int(11) NOT NULL,
  `itemid5` int(11) NOT NULL,
  `amount5` int(11) NOT NULL,
  `itemid6` int(11) NOT NULL,
  `amount6` int(11) NOT NULL,
  `itemid7` int(11) NOT NULL,
  `amount7` int(11) NOT NULL,
  `itemid8` int(11) NOT NULL,
  `amount8` int(11) NOT NULL,
  `itemid9` int(11) NOT NULL,
  `amount9` int(11) NOT NULL,
  `itemid10` int(11) NOT NULL,
  `amount10` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


CREATE TABLE `admin_generate_item_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `gm_name` varchar(32) NOT NULL,
  `player_name` varchar(32) NOT NULL,
  `rewards_reason` varchar(300) NOT NULL,
  `itemid1` int(11) NOT NULL,
  `amount1` int(11) NOT NULL,
  `itemid2` int(11) NOT NULL,
  `amount2` int(11) NOT NULL,
  `itemid3` int(11) NOT NULL,
  `amount3` int(11) NOT NULL,
  `itemid4` int(11) NOT NULL,
  `amount4` int(11) NOT NULL,
  `itemid5` int(11) NOT NULL,
  `amount5` int(11) NOT NULL,
  `itemid6` int(11) NOT NULL,
  `amount6` int(11) NOT NULL,
  `itemid7` int(11) NOT NULL,
  `amount7` int(11) NOT NULL,
  `itemid8` int(11) NOT NULL,
  `amount8` int(11) NOT NULL,
  `itemid9` int(11) NOT NULL,
  `amount9` int(11) NOT NULL,
  `itemid10` int(11) NOT NULL,
  `amount10` int(11) NOT NULL,
  `date_created` datetime DEFAULT '1900-01-01 00:00:00',
  `date_claimed` datetime DEFAULT '1900-01-01 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;